ipa-kdb: handle dates up to 2106-01-01 00:00
freeipa/freeipa pull request #5288
Opened 2020-11-24 14:21 UTC by ptrNine

krb5 uses negative part of `krb5_timestamp` to store time values after 2038
https://k5wiki.kerberos.org/wiki/Projects/Timestamps_after_2038
In other words, krb5 uses `krb5_timestamp` (signed int) with unsigned arithmetic for expanding of the timestamp time range.

This commit:
- adds some helper functions for working with `krb5_timestamp` as unsigned (actually copied from the link above)
- replaces operations with `krb5_timestamp`'s by these new functions
- sets `IPAPWD_END_OF_TIME` to `4291747200L` (1 Jan 2106, 00:00 GMT)

2020-11-24 14:31 UTC, abbra commented
@ptrNine thanks for the patch. Could you please expand the commit message with the text in the description and also add

```
Fixes: https://pagure.io/freeipa/issue/8028
Signed-off-by: <your sign-off details>
```

2020-11-24 14:31 UTC, abbra commented
@frozencemetery could you please review this?

2020-11-24 20:24 UTC, frozencemetery requested changes
In addition to the comments inline, please ensure you comply to our [code style](https://github.com/freeipa/freeipa/blob/master/daemons/ipa-kdb/README).  In particular, we have a maximum line length of 79 characters.

ipadb_get_ldap_mod_time needs addressed.

2020-11-25 10:52 UTC, ptrNine commented on util/ipa_krb5.h
> +}
Thanks for review!

Is it enough to insert comments with attribution to the author before these functions or should I do more?

(Sorry for this question, I have never encountered this and don't know how to lift a code properly)

2020-12-01 19:56 UTC, frozencemetery commented on util/ipa_krb5.h
> +}
Good question.  I'm not totally sure what IPA project style here is, but you should get reasonably close if you add a comment below the IPA license declaration stating that the krb5 timestamp functions are taken from https://github.com/krb5/krb5/blob/master/src/include/k5-int.h and reproduce the MIT copyright blob with year 2017.

2020-12-18 09:14 UTC, abbra commented
@ptrNine could you please address @frozencemetery comments? We wouldn't be able to get this PR into FreeIPA 4.9.0 as it is too late so next milestone would be 4.9.1 somewhere in late January. If you can get it done by mid-January, it would be really great.

2020-12-18 12:15 UTC, ptrNine commented
Sorry for delay
I have fixed all flaws, but I doubt about the copyright headers in util/ipa_krb5.h

2020-12-18 17:14 UTC, frozencemetery approved these changes
My comments have been addressed, thanks!

2020-12-18 18:39 UTC, abbra commented
master:

* 4c0398433e5707b6067519f9ada72cb697ae225a ipa-kdb: handle dates up to 2106-02-07 06:28:16

2020-12-18 18:39 UTC, closed without merging