Test that IPA certs are removed on server uninstall
freeipa/freeipa pull request #5419
Opened 2021-01-13 11:09 UTC by antoniotorresm

Test that IPA certs are removed after the server uninstall
process.

Addresses: https://pagure.io/freeipa/issue/8614

Signed-off-by: Antonio Torres <antorres@redhat.com>

2021-01-14 11:02 UTC, fcami requested changes

2021-01-14 11:02 UTC, fcami commented on ipatests/pytest_ipa/integration/tasks.py
> +    assert host.run_command("trust list | grep IPA",
You can use shlex for this. You can grep in ipatests/ to see how it works.

2021-01-14 11:17 UTC, fcami commented on ipatests/pytest_ipa/integration/tasks.py
> +    assert host.run_command("trust list | grep IPA",
Or you could fetch the whole output (e.g. not use grep) and use substring matching instead.

2021-01-15 15:09 UTC, rcritten commented on ipatests/pytest_ipa/integration/tasks.py
> +                                            raiseonerr=False).stdout_text
If this command fails this assert will still pass. Dropping the raiseonerr=False will address this. Or you can assign the result to a variable and assert returncode == 0 along with the 'IPA CA' not in stdout_text.

2021-01-15 16:15 UTC, fcami reviewed
LGTM. Please remove the temp commit and I'll ack the PR.

2021-01-15 17:45 UTC, fcami approved these changes
ACK

2021-01-19 10:22 UTC, flo-renaud commented
master:

* 6f830ae1ad1ee62a597bcfad81c9d6a4784c24ee Test that IPA certs are removed on server uninstall
* 79d9790c9954ec6ab97e8285074f6cf41e346879 Check that IPA cert is added to trust store after server install

2021-01-19 10:22 UTC, closed without merging