Use new method in check to prevent removal of last KRA
freeipa/freeipa pull request #5908
Opened 2021-07-20 02:03 UTC by rcritten

It previously used a vault connection to determine if any
KRA servers were installed. This would fail if the last KRA
was not available.
    
Use server roles instead to determine if the last KRA server
is to be removed.
    
https://pagure.io/freeipa/issue/8397
    
Signed-off-by: Rob Crittenden <rcritten@redhat.com>

2021-07-21 15:26 UTC, fcami requested changes
hi @rcritten thanks for the contribution, could you please have a look at my comments?

2021-07-21 15:26 UTC, fcami commented on ipatests/test_integration/test_installation.py
> +            ['ipa', 'server-del', self.master.hostname], raiseonerr=False
Could you use tasks.run_server_del instead?

2021-07-21 15:26 UTC, fcami commented on ipatests/test_integration/test_installation.py
> +    master_with_dns = False
I think this belongs in test_server_del.

2021-07-21 16:45 UTC, fcami commented
/azp run

2021-07-21 18:56 UTC, fcami commented
/azp run

2021-07-21 20:10 UTC, rcritten commented
/azp run

2021-07-21 20:27 UTC, fcami commented
LGTM. ACK for when CI passes. Please post the link to a green CI run and remove the temp commit.

2021-07-21 20:29 UTC, fcami approved these changes
ACK for when CI passes. Please post the link to a green CI run and remove the temp commit, I'll add the ACK.

2021-07-22 13:38 UTC, fcami commented
Green [CI run](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/14c21164-ea63-11eb-ab51-5254008d789d/report.html)

2021-07-22 13:38 UTC, fcami commented
@rcritten from my PoV you can remove the temp commit to start gating instead.

2021-07-22 18:36 UTC, fcami approved these changes
ACK

2021-07-22 18:39 UTC, rcritten commented
master:

* 10bd66dd1a14fc0bd39c489d0d0af76b0f720c96 Use new method in check to prevent removal of last KRA
* 2097776e5e5d699575d0dc0e7006b5e50fbc6f9e ipatests: test removing last KRA when it is not running

2021-07-22 18:39 UTC, closed without merging