ipatests: test_subids: test subid-match shows UID of the owner
freeipa/freeipa pull request #6106
Opened 2021-11-24 14:50 UTC by miskopo

ipa subid-match should show UID of the owner instead of DN.

Related: https://pagure.io/freeipa/issue/8977

Signed-off-by: Michal Polovka <mpolovka@redhat.com>

2021-12-15 12:53 UTC, amore17 requested changes

2021-12-15 12:53 UTC, amore17 commented on ipatests/test_integration/test_subids.py
> +                                          f"--subuid={subuid}", "--raw"])
Hi @miskopo Thanks for the patch.
Could you try this without adding `--raw`

2022-06-01 10:13 UTC, amore17 commented
@miskopo Thanks for the patch.
Do we need back-port ? 
You can remove temp_commit I'll ack once all tests green.

2022-06-01 10:16 UTC, miskopo commented
Backport to `ipa-4-9` added. Link to [temp commit](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/e78fc338-e18f-11ec-b5fe-fa163ea4a9f1)

2022-06-01 11:54 UTC, miskopo commented
master:

* c18caaa7aa3fdb6ae648474f92b28a053eab434a ipatests: test_subids: test subid-match shows UID of the owner

2022-06-01 11:54 UTC, closed without merging