ipatests : local ca is not generated under fips
freeipa/freeipa pull request #6112
Opened 2021-11-26 07:28 UTC by ssidhaye

Certmonger uses default OpenSSL encryption algorithms
to generate the PKCS12 object used for the local CA.
This uses operations that are disallowed under fips,
and so the local ca pkcs12 creds file is not generated.

Bugzilla Link:  https://bugzilla.redhat.com/show_bug.cgi?id=1950132

Signed-off-by: Sumedh Sidhaye <ssidhaye@redhat.com>

2021-11-26 08:18 UTC, fcami requested changes
Please change the commit message with a ticket number, not a bz link.
Please explain what the expected behavior is in the commit message and what the previous, buggy behavior was.

2021-11-26 11:25 UTC, ssidhaye commented
I have updated the commit message. As for the ticket link all I could find was https://pagure.io/certmonger/pull-request/198 , I could not find a ticket. @rcritten is there a pagure ticket link for this fix ?

2021-11-29 16:41 UTC, rcritten commented
I think I can address automation directly in certmonger rather than in IPA. Let me see what is involved.

2021-11-29 19:12 UTC, rcritten commented
Here is my proposal to fix this in the certmonger unit tests, https://pagure.io/certmonger/pull-request/232

2021-11-30 06:44 UTC, ssidhaye commented
I don't mind including it in certmonger repo itself. Is it tested as part of freeipa CI ?

2021-11-30 14:38 UTC, rcritten commented
No but the problem doesn't apply to IPA which doesn't use the local CA helper.

2022-02-13 04:21 UTC, closed without merging