ipatests: Add integration tests for External IdP support
freeipa/freeipa pull request #6263
Opened 2022-05-17 13:46 UTC by amore17

Tests for [RFE]: Added integration tests for external IdP
authentication with keycloak-17 as identity provider.

Related : https://pagure.io/freeipa/issue/8805
Related: https://pagure.io/freeipa/issue/8803
Related: https://pagure.io/freeipa/issue/8804

2022-05-18 05:47 UTC, abbra requested changes
Thank you for the PR! I have only one change requested -- remove permissive mode, it is not really required.

2022-05-18 05:47 UTC, abbra commented on ipatests/pytest_ipa/integration/create_quarkus.py
> +    host.run_command(["setenforce", "0"])
In my tests this was not needed, as long as you relabel content in /opt/keycloak with `restorecon -R /opt/keycloak'.

2022-05-19 08:47 UTC, mrizwan93 requested changes
Hello @amore17 
Please fine comments inline.

2022-05-19 08:58 UTC, abbra commented on ipatests/pytest_ipa/integration/create_quarkus.py
> +    keystore = "/etc/pki/tls/private/keycloak.store"
Why? These do not belong to the runtime, they are part of the test environment.

2022-05-19 10:29 UTC, amore17 commented on ipatests/pytest_ipa/integration/create_quarkus.py
> +    keystore = "/etc/pki/tls/private/keycloak.store"
Yes they are related to test environment.

2022-05-19 11:17 UTC, amore17 commented
Tested also in idm-ci environment using @freeipa/freeipa-master-nightly

2022-05-19 11:29 UTC, amore17 commented
[logs](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/86ba931c-d758-11ec-9976-fa163e0ccb17)

2022-05-19 12:46 UTC, abbra commented
LGTM. I'll add ACK after the remaning two tests complete.

2022-05-23 05:39 UTC, abbra commented
master:

* 5ca4e8ee33cb2de7f0e05b91dfe9cc41829609cd pr-ci definitions: add external idp related jobs.
* 9cc703fd0ed1afc24dc865ed967264c7f7340ac7 ipatests: Add integration tests for External IdP support

2022-05-23 05:39 UTC, closed without merging

2022-05-23 05:40 UTC, abbra commented
@amore17 please submit a manual backport, automation failed to create a clean merge to ipa-4-9.