WIP: ipatests:  allow to query the AD specific attributes for a user or a group directly
freeipa/freeipa pull request #6375
Opened 2022-07-25 11:37 UTC by menonsudhir

The testscase adds an additional attribute info: mytest for AD group which is similar to the user name 'mytest'
and make sure that the getent group should display the output on ipa-client

2022-07-27 06:25 UTC, amore17 requested changes

2022-07-27 06:25 UTC, amore17 commented on ipatests/prci_definitions/temp_commit.yaml
> +        topology: &ad_master_2client
Please use *ad_master_2client

2022-08-06 06:14 UTC, flo-renaud commented on ipatests/test_integration/test_trust.py
> +        """).format(base_dn=base_dn)
The call to format() also needs to provide a value for adgroup.

2022-10-12 11:47 UTC, flo-renaud commented
@menonsudhir can this PR be closed in favor of #6499 ?

2022-10-12 11:58 UTC, menonsudhir commented
> @menonsudhir can this PR be closed in favor of #6499 ?

@flo-renaud yes closing this PR.

2022-10-12 11:58 UTC, closed without merging