Add test for grace login limit
freeipa/freeipa pull request #6513
Opened 2022-10-17 09:11 UTC by b3lix

2022-11-04 13:02 UTC, miskopo requested changes
Please see the inline comments

2022-11-04 13:02 UTC, miskopo commented on ipatests/test_webui/test_user.py
> +
add
```
        try:
            # click save if needed
            self.button_click('save')
        except AssertionError:
            # autosave active
            pass
```
 after modifying `pwpolicy`

2022-11-07 13:55 UTC, miskopo requested changes

2022-11-07 13:55 UTC, miskopo commented on ipatests/test_webui/test_user.py
> +import ipatests.test_webui.data_pwpolicy as pwpolicy
just a nitpick, but there was a space before and also, the imports are in alphabetical order

2022-11-07 14:52 UTC, miskopo commented
Great success! 

Please, provide links to the temp commits as a comment, remove the temp commit and I'll `ACK` when the CI finishes... **If** it finishes.

2022-11-07 15:23 UTC, b3lix commented
[temp_commit_pwpolicy](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/a6a8ca92-5ea6-11ed-a070-fa163e86d7ce/)
[temp_commit_user](http://freeipa-org-pr-ci.s3-website.eu-central-1.amazonaws.com/jobs/953b7d36-5ea6-11ed-b17b-fa163ed0f469)

2022-11-08 13:24 UTC, miskopo commented
One last thing - in the commit message, you point to this very PR, however, the link should point to https://pagure.io/freeipa/issue/9211

2022-11-08 13:24 UTC, miskopo requested changes
Please see the comment above

2022-11-09 09:23 UTC, miskopo commented
All is fine, now, seriously one last thing - please rebase this branch on top of upstream master to avoid potential conflicts

2022-11-10 08:31 UTC, miskopo commented
master:

* d6a643b798deb673fa94bf8278fb291b42314562 ipatests: Add test for grace login limit

2022-11-10 08:31 UTC, closed without merging