WIP: ipatests: ipa-automountlocation tests
freeipa/freeipa pull request #6788
Opened 2023-04-19 11:36 UTC by menonsudhir

This patch includes tests for ipa-automountlocation commands

2023-08-28 07:51 UTC, amore17 commented
IMO its suitable in xmlrpc tests.

2023-08-28 07:52 UTC, amore17 requested changes

2023-08-28 07:52 UTC, amore17 commented on ipatests/test_integration/test_nfs.py
> +        assert cmd.returncode == 0
This assert not required by default its asserting already.

2023-09-14 07:14 UTC, flo-renaud commented
Hi @menonsudhir 
the tests should be added to the xmlrpc tests as they mainly test the CLI.
You need to check which ones are already available in ipatests/test_xmlrpc/test_automount_plugin.py and add only the missing ones.

2023-09-14 12:07 UTC, menonsudhir commented
Closing this PR as this will be redone in xmlrpc tests.

2023-09-14 12:07 UTC, closed without merging