ipatests: Tests for RBCD feature
freeipa/freeipa pull request #6882
Opened 2023-06-15 08:43 UTC by miskopo

Integration tests for RBCD feature.

Related: xxx

2023-06-16 11:43 UTC, miskopo commented
@abbra could you please take a look at this test proposal?

2023-06-20 10:38 UTC, abbra requested changes
I left few comments.

2023-06-20 10:38 UTC, abbra commented on ipatests/test_integration/test_rbcd.py
> +                                      extra_args=['--two-way=false'])
You must use `--two-way=true` for any cross-realm S4U scenarios. Please see https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-sfu/1fb9caca-449f-4183-8f7a-1a5fc7e7290a and https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-sfu/f35b6902-6f5e-4cd0-be64-c50bbaaf54a5 for more details.

2023-06-20 10:38 UTC, abbra commented on ipatests/test_integration/test_rbcd.py
> +        cmd = ('Set-ADComputer -Identity {} -PrincipalsAllowedToDelegateToAccount '{}).format(service_name, ipa_service)
This is the part that will not work currently. Powershell commands cannot resolve IPA services in any way and `Set-ADComputer` cannot take SID of IPA service. I am still investigating how we can define that list...

2023-10-15 13:14 UTC, closed without merging