Issue 9547 - Update IPA to IPA migration design doc
freeipa/freeipa pull request #7255
Opened 2024-02-28 15:48 UTC by mreynolds389

Update the ipa to ipa migration doc in regards to the new IPA migration tool

Fixes: https://pagure.io/freeipa/issue/9547

2024-02-29 12:40 UTC, flo-renaud commented
@mreynolds389 the failure of `test_commands` is related to feb 29, please see [9548](https://pagure.io/freeipa/issue/9548). Re-run the test tomorrow and it should succeed.

2024-03-04 09:20 UTC, abbra requested changes
I have one small inline comment and larger, here. 

I think it will be more clear if instead of comma-prefixed DNs you'd write a 'subtree of ...', e.g. 

> Topology (,cn=topology,cn=ipa,cn=etc,$SUFFIX)

would become

> Topology (subtree of `cn=topology,cn=ipa,cn=etc,$SUFFIX`)

This syntax (DN with preceding `,`) is not described anywhere in the document and is not used elsewhere in IPA design documents (nor in LDAP specifications), so it is not immediately clear what does it mean.

2024-03-04 13:02 UTC, mreynolds389 commented on doc/designs/ipa_to_ipa_migration.md
> +{% include toc.md %}
> this include is not needed. ReadTheDocs automatically adds table of contents.

Great, good to know!

2024-03-04 13:05 UTC, mreynolds389 commented
> I have one small inline comment and larger, here.
> 
> I think it will be more clear if instead of comma-prefixed DNs you'd write a 'subtree of ...', e.g.
> 
> > Topology (,cn=topology,cn=ipa,cn=etc,$SUFFIX)
> 
> would become
> 
> > Topology (subtree of `cn=topology,cn=ipa,cn=etc,$SUFFIX`)
> 
> This syntax (DN with preceding `,`) is not described anywhere in the document and is not used elsewhere in IPA design documents (nor in LDAP specifications), so it is not immediately clear what does it mean.

Right it's not a specification, but it's how it's used in the tool's code.  There are comments in the doc stating that if it starts with a comma then it's a subtree.  Regardless I will gladly change the document to make it more clear

2024-03-05 16:48 UTC, mreynolds389 commented
> > I have one small inline comment and larger, here.
> > I think it will be more clear if instead of comma-prefixed DNs you'd write a 'subtree of ...', e.g.
> > > Topology (,cn=topology,cn=ipa,cn=etc,$SUFFIX)
> > 
> > 
> > would become
> > > Topology (subtree of `cn=topology,cn=ipa,cn=etc,$SUFFIX`)
> > 
> > 
> > This syntax (DN with preceding `,`) is not described anywhere in the document and is not used elsewhere in IPA design documents (nor in LDAP specifications), so it is not immediately clear what does it mean.

@abbra changes made, please review

2024-03-13 14:25 UTC, mreynolds389 commented
@abbra I don't have authorization to merge :-)

2024-03-13 14:28 UTC, abbra commented
@mreynolds389 don't worry, this will be handled by the people who have those rights. We do not use github for this, github repo is only for raising PRs.

2024-03-14 12:58 UTC, flo-renaud commented
As the original PR adding the migration doc (#7078) was backported to ipa-4-10 and ipa-4-11, I am also adding the labels.

2024-03-14 13:03 UTC, flo-renaud commented
master:

* 557f0a5639e65b952ed0ce82e4ef42683bf75178 Issue 9547 - Update IPA to IPA migration design doc

2024-03-14 13:03 UTC, closed without merging